default_env: &default_env
  MAIL_HOST: 'localhost:3000'
  LICENSE-KEY: '0c2e13558920e3238e50b1b0957ce333cbdc1429'

development:
  env:
    <<: *default_env

test:
  env:
    <<: *default_env

production:
  env:
    MAIL_HOST: 'http://send-it.herokuapp.com'